import { gemini } from "./gemini.ts";
import type { Script } from "./script.ts";
import type { Research } from "./research.ts";
import { normalizeMotionStyle, normalizeSceneType, type MotionStyle, type SceneType } from "./video-style.ts";

export interface Scene {
  timestamp: number;
  duration: number;
  imagePrompt: string;
  searchQuery?: string;
  sceneType?: SceneType;
  headline?: string;
  emphasis?: string;
  motion?: MotionStyle;
}

export async function generateScenes(
  script: Script,
  research: Research,
  totalDuration: number,
  isShort = true
): Promise<Scene[]> {
  const prompt = `You are a visual director for viral documentary YouTube Shorts.
Given this script and research, partition the entire video into consecutive visual scenes.

Script:
"${script.full}"

Research Summary:
"${research.summary}"

Timeline:
${(research.timeline ?? []).map((t) => `- ${t.year}: ${t.event}`).join("\n") || "No specific timeline available."}

Video Duration: ${totalDuration.toFixed(2)} seconds.

Rules for Scene Generation:
1. Divide the video into consecutive scenes.
2. The first scene must start at timestamp 0.
3. The sum of all scene durations MUST exactly equal ${totalDuration.toFixed(2)} seconds.
4. Each scene duration should be: ${isShort ? "strictly between 1.5 and 2.5 seconds (so there are more cuts and the pacing is extremely fast and engaging)" : "between 3.0 and 6.0 seconds"}.
5. Provide a detailed, highly cinematic, photographic image prompt (imagePrompt) for each scene. The style should be documentary-style, dramatic, with high contrast. Use descriptive details rather than buzzwords.
6. The scenes must follow the chronological flow of the script.
7. The imagePrompts should generate images suited for a ${isShort ? "9:16 vertical" : "16:9 horizontal"} aspect ratio.
8. Use sceneType to create editorial variety. Pick one of: "image", "headline", "stat", "quote", "timeline", "comparison".
9. headline should be a short on-screen editorial label, 3-8 words max.
10. emphasis should be the strongest word, year, number, company, or phrase to highlight.
11. motion should be one of: "zoom-in", "zoom-out", "pan-left", "pan-right", "pan-up".

Return ONLY JSON matching:
{
  "scenes": [
    {
      "timestamp": number, // start time in seconds
      "duration": number,  // duration of the scene in seconds
      "imagePrompt": string, // descriptive prompt for an AI image generator (e.g. "9:16 cinematic portrait of...")
      "searchQuery": string, // 3-4 descriptive keywords to search for a stock photo of this scene (e.g. "Nokia 3310 phone", "Blockbuster store outside")
      "sceneType": string,
      "headline": string,
      "emphasis": string,
      "motion": string
    }
  ]
}`;

  const raw = await gemini(prompt, { json: true });
  const parsed = JSON.parse(raw) as { scenes: Scene[] };

  // Post-process to ensure durations match totalDuration exactly and starts are aligned
  const scenes = parsed.scenes;
  if (!scenes || scenes.length === 0) {
    throw new Error("No scenes generated by LLM");
  }

  // Enforce timing integrity
  let currentTimestamp = 0;
  for (let i = 0; i < scenes.length; i++) {
    scenes[i].timestamp = Math.round(currentTimestamp * 100) / 100;
    // For the last scene, make sure it fills the remaining duration
    if (i === scenes.length - 1) {
      scenes[i].duration = Math.round((totalDuration - currentTimestamp) * 100) / 100;
    } else {
      scenes[i].duration = Math.round(scenes[i].duration * 100) / 100;
    }
    scenes[i].sceneType = normalizeSceneType(scenes[i].sceneType);
    scenes[i].motion = normalizeMotionStyle(scenes[i].motion, i);
    scenes[i].headline = (scenes[i].headline || "").trim();
    scenes[i].emphasis = (scenes[i].emphasis || "").trim();
    currentTimestamp += scenes[i].duration;
  }

  return scenes;
}

async function searchImageDDG(query: string): Promise<string | null> {
  try {
    const searchUrl = `https://duckduckgo.com/?q=${encodeURIComponent(query)}`;
    const response = await fetch(searchUrl);
    if (!response.ok) return null;
    const html = await response.text();

    const vqdRegex = /vqd=["']([^"']+)["']/;
    const match = html.match(vqdRegex);
    if (!match) return null;
    const vqd = match[1];

    const imagesUrl = `https://duckduckgo.com/i.js?l=us-en&o=json&q=${encodeURIComponent(query)}&vqd=${vqd}`;
    const imgResponse = await fetch(imagesUrl);
    if (!imgResponse.ok) return null;
    const data = await imgResponse.json() as any;

    if (data.results && data.results.length > 0) {
      return data.results[0].image;
    }
  } catch (error) {
    console.warn("⚠️ DuckDuckGo image search failed:", error);
  }
  return null;
}

const downloadedUrls = new Set<string>();

async function searchImageBing(query: string): Promise<string | null> {
  try {
    const url = `https://www.bing.com/images/search?q=${encodeURIComponent(query)}`;
    const headers = {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Cookie": "SRCHHPGUSR=ADLT=STRICT",
    };

    console.log(`     🔍 Searching Bing for related image: "${query}"...`);
    const response = await fetch(url, { headers });
    if (!response.ok) return null;
    const html = await response.text();

    const regex = /&quot;murl&quot;:&quot;(https?:[^&]+)&quot;/g;
    const matches = Array.from(html.matchAll(regex)).map(m => m[1]);

    if (matches.length > 0) {
      if (downloadedUrls.size > 1000) {
        downloadedUrls.clear();
      }
      for (const imageUrl of matches) {
        if (!downloadedUrls.has(imageUrl)) {
          downloadedUrls.add(imageUrl);
          return imageUrl;
        }
      }
      const randomIndex = Math.floor(Math.random() * Math.min(5, matches.length));
      return matches[randomIndex];
    }
  } catch (error) {
    console.warn("⚠️ Bing image search failed:", error);
  }
  return null;
}

function cleanSearchQuery(prompt: string): string {
  let cleaned = prompt;

  cleaned = cleaned.replace(/[\[\]\(\)\-\*]/g, " ");

  const ignorePatterns = [
    /^(a|an|the)\s+/i,
    /^(9:16|16:9|vertical|horizontal|cinematic|dramatic|photographic|split|close[ -]?up|extreme close[ -]?up|wide[ -]?shot|establishing[ -]?shot|high[ -]?contrast|moody)\s+/i,
    /^(portrait|photograph|image|illustration|artistic rendering|photo|picture|depiction|scene|view|shot) of\s+/i,
    /^(a|an|the)\s+/i,
  ];

  let prev;
  do {
    prev = cleaned;
    for (const pattern of ignorePatterns) {
      cleaned = cleaned.replace(pattern, "").trim();
    }
  } while (cleaned !== prev);

  const splitters = [",", ".", ";", " with ", " showing ", " against ", " in front of ", " lying on ", " sitting on "];
  let cutIndex = -1;
  for (const splitter of splitters) {
    const idx = cleaned.toLowerCase().indexOf(splitter);
    if (idx !== -1) {
      if (cutIndex === -1 || idx < cutIndex) {
        cutIndex = idx;
      }
    }
  }

  if (cutIndex !== -1) {
    cleaned = cleaned.substring(0, cutIndex).trim();
  }

  const words = cleaned.split(/\s+/).filter(w => w.trim().length > 0);
  if (words.length > 5) {
    cleaned = words.slice(0, 5).join(" ");
  }

  return cleaned.trim() || prompt.split(/\s+/).slice(0, 4).join(" ");
}

export async function downloadImage(prompt: string, outputPath: string, isShort = true, searchQueryOverride?: string): Promise<void> {
  const provider = process.env.IMAGE_PROVIDER || "placeholder";

  if (provider === "local_sd") {
    try {
      const url = process.env.LOCAL_SD_URL || "http://127.0.0.1:7860";
      const endpoint = `${url}/sdapi/v1/txt2img`;
      console.log(`     🎨 Generating image locally via Stable Diffusion API...`);

      // Determine dimensions based on prompt aspect ratio suggestion
      const width = isShort ? 540 : 960;
      const height = isShort ? 960 : 540;

      const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: prompt,
          negative_prompt: "blurry, low quality, distorted, pixelated, worst quality, text, watermark, signature",
          steps: 20,
          cfg_scale: 7,
          width: width,
          height: height,
        }),
      });

      if (!res.ok) {
        throw new Error(`Local Stable Diffusion failed: ${res.status} ${await res.text()}`);
      }

      const data = (await res.json()) as { images: string[] };
      if (data.images?.[0]) {
        const base64Data = data.images[0];
        const binaryString = atob(base64Data);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }
        await Bun.write(outputPath, bytes.buffer);
        return;
      }
      throw new Error("No image data returned by local Stable Diffusion");
    } catch (error) {
      console.warn(`     ⚠️ Local Stable Diffusion failed, falling back to placeholder:`, error);
    }
  }

  const replicateKey = process.env.REPLICATE_API_KEY;
  const openaiKey = process.env.OPENAI_API_KEY;

  if (provider === "replicate" && replicateKey) {
    try {
      console.log(`     🎨 Generating image via Replicate (Flux)...`);
      // Start prediction
      const startRes = await fetch("https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions", {
        method: "POST",
        headers: {
          Authorization: `Token ${replicateKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          input: {
            prompt: prompt,
            aspect_ratio: "9:16",
            output_format: "jpg"
          },
        }),
      });

      if (!startRes.ok) {
        throw new Error(`Replicate start failed: ${startRes.status} ${await startRes.text()}`);
      }

      let prediction = (await startRes.json()) as any;
      const id = prediction.id;

      // Poll until succeeded
      console.log(`     ⏳ Waiting for Replicate image generation (ID: ${id})...`);
      let attempts = 0;
      while (prediction.status !== "succeeded" && prediction.status !== "failed" && attempts < 30) {
        await new Promise((resolve) => setTimeout(resolve, 1000));
        attempts++;
        const pollRes = await fetch(`https://api.replicate.com/v1/predictions/${id}`, {
          headers: { Authorization: `Token ${replicateKey}` },
        });
        if (pollRes.ok) {
          prediction = await pollRes.json();
        }
      }

      if (prediction.status === "succeeded" && prediction.output?.[0]) {
        const imageUrl = prediction.output[0];
        const imgRes = await fetch(imageUrl);
        if (imgRes.ok) {
          await Bun.write(outputPath, await imgRes.arrayBuffer());
          return;
        }
      }
      throw new Error(`Replicate prediction failed or timed out: ${prediction.error || "unknown error"}`);
    } catch (error) {
      console.warn(`     ⚠️ Replicate failed, falling back to placeholder:`, error);
    }
  }

  if (provider === "openai" && openaiKey) {
    try {
      console.log(`     🎨 Generating image via OpenAI (DALL-E 3)...`);
      const res = await fetch("https://api.openai.com/v1/images/generations", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${openaiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "dall-e-3",
          prompt: prompt,
          n: 1,
          size: "1024x1792", // 9:16 portrait ratio
        }),
      });

      if (!res.ok) {
        throw new Error(`OpenAI image generation failed: ${res.status} ${await res.text()}`);
      }

      const data = (await res.json()) as any;
      const imageUrl = data.data?.[0]?.url;
      if (imageUrl) {
        const imgRes = await fetch(imageUrl);
        if (imgRes.ok) {
          await Bun.write(outputPath, await imgRes.arrayBuffer());
          return;
        }
      }
      throw new Error("No image URL returned by OpenAI");
    } catch (error) {
      console.warn(`     ⚠️ OpenAI image generation failed, falling back to placeholder:`, error);
    }
  }

  if (provider === "placeholder") {
    const searchQuery = searchQueryOverride ?? cleanSearchQuery(prompt);
    let searchResultUrl = await searchImageBing(searchQuery);

    if (!searchResultUrl) {
      console.log(`     🔍 Fallback: Searching DuckDuckGo for related image: "${searchQuery}"...`);
      searchResultUrl = await searchImageDDG(searchQuery);
    }

    if (searchResultUrl) {
      try {
        console.log(`     📥 Downloading related image from: ${searchResultUrl}`);
        const imgRes = await fetch(searchResultUrl, {
          headers: {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
          }
        });
        const contentType = imgRes.headers.get("content-type") || "";
        if (imgRes.ok && contentType.startsWith("image/")) {
          await Bun.write(outputPath, await imgRes.arrayBuffer());
          return;
        } else {
          console.warn(`     ⚠️ Download failed or returned non-image content type "${contentType}" (status ${imgRes.status}), falling back to Picsum...`);
        }
      } catch (err) {
        console.warn(`     ⚠️ Image download failed, falling back to Picsum...`, err);
      }
    }
  }

  // Fallback to Picsum placeholder
  console.log(`     🖼️  Downloading Picsum placeholder image...`);
  const resolution = isShort ? "1080/1920" : "1920/1080";
  const picsumRes = await fetch(`https://picsum.photos/${resolution}?random=${Math.random()}`);
  if (!picsumRes.ok) {
    throw new Error(`Failed to download placeholder: ${picsumRes.status}`);
  }
  await Bun.write(outputPath, await picsumRes.arrayBuffer());
}
