import { gemini } from "./gemini.ts";
import type { Script } from "./script.ts";
import type { Research } from "./research.ts";

export interface Scene {
  timestamp: number;
  duration: number;
  imagePrompt: string;
}

export async function generateScenes(
  script: Script,
  research: Research,
  totalDuration: number
): Promise<Scene[]> {
  const prompt = `You are a visual director for viral documentary YouTube Shorts.
Given this script and research, partition the entire video into consecutive visual scenes.

Script:
"${script.full}"

Research Summary:
"${research.summary}"

Timeline:
${research.timeline.map((t) => `- ${t.year}: ${t.event}`).join("\n")}

Video Duration: ${totalDuration.toFixed(2)} seconds.

Rules for Scene Generation:
1. Divide the video into consecutive scenes.
2. The first scene must start at timestamp 0.
3. The sum of all scene durations MUST exactly equal ${totalDuration.toFixed(2)} seconds.
4. Each scene duration should be between 3.0 and 6.0 seconds.
5. Provide a detailed, highly cinematic, photographic image prompt (imagePrompt) for each scene. The style should be documentary-style, dramatic, with high contrast. Use descriptive details rather than buzzwords.
6. The scenes must follow the chronological flow of the script.

Return ONLY JSON matching:
{
  "scenes": [
    {
      "timestamp": number, // start time in seconds
      "duration": number,  // duration of the scene in seconds
      "imagePrompt": string // descriptive prompt for an AI image generator (e.g. "9:16 cinematic portrait of...")
    }
  ]
}`;

  const raw = await gemini(prompt, { json: true });
  const parsed = JSON.parse(raw) as { scenes: Scene[] };

  // Post-process to ensure durations match totalDuration exactly and starts are aligned
  const scenes = parsed.scenes;
  if (!scenes || scenes.length === 0) {
    throw new Error("No scenes generated by LLM");
  }

  // Enforce timing integrity
  let currentTimestamp = 0;
  for (let i = 0; i < scenes.length; i++) {
    scenes[i].timestamp = Math.round(currentTimestamp * 100) / 100;
    // For the last scene, make sure it fills the remaining duration
    if (i === scenes.length - 1) {
      scenes[i].duration = Math.round((totalDuration - currentTimestamp) * 100) / 100;
    } else {
      scenes[i].duration = Math.round(scenes[i].duration * 100) / 100;
    }
    currentTimestamp += scenes[i].duration;
  }

  return scenes;
}

export async function downloadImage(prompt: string, outputPath: string): Promise<void> {
  const provider = process.env.IMAGE_PROVIDER || "placeholder";

  if (provider === "local_sd") {
    try {
      const url = process.env.LOCAL_SD_URL || "http://127.0.0.1:7860";
      const endpoint = `${url}/sdapi/v1/txt2img`;
      console.log(`     🎨 Generating image locally via Stable Diffusion API...`);

      // Determine dimensions based on prompt aspect ratio suggestion
      const isShort = !prompt.includes("16:9");
      const width = isShort ? 540 : 960;
      const height = isShort ? 960 : 540;

      const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: prompt,
          negative_prompt: "blurry, low quality, distorted, pixelated, worst quality, text, watermark, signature",
          steps: 20,
          cfg_scale: 7,
          width: width,
          height: height,
        }),
      });

      if (!res.ok) {
        throw new Error(`Local Stable Diffusion failed: ${res.status} ${await res.text()}`);
      }

      const data = (await res.json()) as { images: string[] };
      if (data.images?.[0]) {
        const base64Data = data.images[0];
        const binaryString = atob(base64Data);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }
        await Bun.write(outputPath, bytes.buffer);
        return;
      }
      throw new Error("No image data returned by local Stable Diffusion");
    } catch (error) {
      console.warn(`     ⚠️ Local Stable Diffusion failed, falling back to placeholder:`, error);
    }
  }

  const replicateKey = process.env.REPLICATE_API_KEY;
  const openaiKey = process.env.OPENAI_API_KEY;

  if (provider === "replicate" && replicateKey) {
    try {
      console.log(`     🎨 Generating image via Replicate (Flux)...`);
      // Start prediction
      const startRes = await fetch("https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions", {
        method: "POST",
        headers: {
          Authorization: `Token ${replicateKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          input: {
            prompt: prompt,
            aspect_ratio: "9:16",
            output_format: "jpg"
          },
        }),
      });

      if (!startRes.ok) {
        throw new Error(`Replicate start failed: ${startRes.status} ${await startRes.text()}`);
      }

      let prediction = (await startRes.json()) as any;
      const id = prediction.id;

      // Poll until succeeded
      console.log(`     ⏳ Waiting for Replicate image generation (ID: ${id})...`);
      let attempts = 0;
      while (prediction.status !== "succeeded" && prediction.status !== "failed" && attempts < 30) {
        await new Promise((resolve) => setTimeout(resolve, 1000));
        attempts++;
        const pollRes = await fetch(`https://api.replicate.com/v1/predictions/${id}`, {
          headers: { Authorization: `Token ${replicateKey}` },
        });
        if (pollRes.ok) {
          prediction = await pollRes.json();
        }
      }

      if (prediction.status === "succeeded" && prediction.output?.[0]) {
        const imageUrl = prediction.output[0];
        const imgRes = await fetch(imageUrl);
        if (imgRes.ok) {
          await Bun.write(outputPath, await imgRes.arrayBuffer());
          return;
        }
      }
      throw new Error(`Replicate prediction failed or timed out: ${prediction.error || "unknown error"}`);
    } catch (error) {
      console.warn(`     ⚠️ Replicate failed, falling back to placeholder:`, error);
    }
  }

  if (provider === "openai" && openaiKey) {
    try {
      console.log(`     🎨 Generating image via OpenAI (DALL-E 3)...`);
      const res = await fetch("https://api.openai.com/v1/images/generations", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${openaiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "dall-e-3",
          prompt: prompt,
          n: 1,
          size: "1024x1792", // 9:16 portrait ratio
        }),
      });

      if (!res.ok) {
        throw new Error(`OpenAI image generation failed: ${res.status} ${await res.text()}`);
      }

      const data = (await res.json()) as any;
      const imageUrl = data.data?.[0]?.url;
      if (imageUrl) {
        const imgRes = await fetch(imageUrl);
        if (imgRes.ok) {
          await Bun.write(outputPath, await imgRes.arrayBuffer());
          return;
        }
      }
      throw new Error("No image URL returned by OpenAI");
    } catch (error) {
      console.warn(`     ⚠️ OpenAI image generation failed, falling back to placeholder:`, error);
    }
  }

  // Fallback to Picsum placeholder
  console.log(`     🖼️  Downloading Picsum placeholder image...`);
  const picsumRes = await fetch("https://picsum.photos/1080/1920");
  if (!picsumRes.ok) {
    throw new Error(`Failed to download placeholder: ${picsumRes.status}`);
  }
  await Bun.write(outputPath, await picsumRes.arrayBuffer());
}
